// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	ports "github.com/lucasbrito3001/url_shortner/internal/app/ports"
	mock "github.com/stretchr/testify/mock"
)

// RedirectUrlUseCase is an autogenerated mock type for the RedirectUrlUseCase type
type RedirectUrlUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, req
func (_m *RedirectUrlUseCase) Execute(ctx context.Context, req *ports.RedirectUrlRequest) (*ports.RedirectUrlResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *ports.RedirectUrlResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ports.RedirectUrlRequest) (*ports.RedirectUrlResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ports.RedirectUrlRequest) *ports.RedirectUrlResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.RedirectUrlResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ports.RedirectUrlRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRedirectUrlUseCase creates a new instance of RedirectUrlUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedirectUrlUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedirectUrlUseCase {
	mock := &RedirectUrlUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
