// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	ports "github.com/lucasbrito3001/url_shortner/internal/app/ports"
	mock "github.com/stretchr/testify/mock"
)

// ShortenUrlUseCase is an autogenerated mock type for the ShortenUrlUseCase type
type ShortenUrlUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, request
func (_m *ShortenUrlUseCase) Execute(ctx context.Context, request *ports.ShortenUrlRequest) (*ports.ShortenUrlResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *ports.ShortenUrlResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ports.ShortenUrlRequest) (*ports.ShortenUrlResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ports.ShortenUrlRequest) *ports.ShortenUrlResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.ShortenUrlResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ports.ShortenUrlRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShortenUrlUseCase creates a new instance of ShortenUrlUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortenUrlUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortenUrlUseCase {
	mock := &ShortenUrlUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
