// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/lucasbrito3001/url_shortner/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// UrlRepository is an autogenerated mock type for the UrlRepository type
type UrlRepository struct {
	mock.Mock
}

// FindByCode provides a mock function with given fields: ctx, code
func (_m *UrlRepository) FindByCode(ctx context.Context, code domain.Code) (*domain.ShortenedUrl, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *domain.ShortenedUrl
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Code) (*domain.ShortenedUrl, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Code) *domain.ShortenedUrl); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ShortenedUrl)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Code) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, url
func (_m *UrlRepository) Save(ctx context.Context, url *domain.ShortenedUrl) error {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ShortenedUrl) error); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUrlRepository creates a new instance of UrlRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlRepository {
	mock := &UrlRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
