FROM golang:1.25.5 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o api ./cmd/api/main.go

FROM alpine:3.23.2
WORKDIR /app

COPY --from=builder /app/api .

EXPOSE 8080

CMD ["./api"]
